import Head from "next/head";
import { Navbar } from "../components/navbar";
import { Footer } from "../components/footer";
import Hero from "../components/hero";
import { About } from "../components/about";
import { Products } from "../components/products";
import { Featured } from "../components/featured";
import { Blogs } from "../components/blogs";
import { Bottom } from "../components/bottom";
import { BlogWidget } from "../components/blogWidget";

import { fetchAPI } from "../lib/api";
import { Article } from "../types/article";
import Image from "next/image";
import Navbar2 from "../components/navbar2";
import Hero2 from "../components/hero2";

// importing products
import products from "../products.json";
import { fromImageToUrl } from "../utils/url";

export interface HomeProps {
  articles?: Article[];
  products?: Product[];
}

export default function Home(props: HomeProps) {
  // Use the first 4 articles as featured articles
  const featuredArticles = props.articles ? props.articles.slice(0, 4) : [];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar /> */}
      <Navbar2 isSignedIn={true} />
      {/* <div>Some body that I used to know</div> */}
      <Hero />
      {/* <Hero2 /> */}
      <About />
      <Products />
      <Featured />
      {/* <Blogs articles={props.articles} /> */}
      {/* Featured Blogs? */}
      <div className={"flex  bg-white-800 p-2"}>
        {featuredArticles.map((entry) => {
          return <BlogWidget key={entry.id} article={entry} />;
        })}
      </div>

      {/* mapping products */}

      {products.map((product) => (
        <div key={product.name} className={"flex flex-row  bg-gray-400 p-2"}>
          <div className={"flex flex-col"}>
            {/* <div className={"flex flex-col"}>
              <img src={fromImageToUrl(product.image)} /> */}
            <image src={fromImageToUrl(product.image)} />
            {product.name} {product.price}
          </div>
        </div>
      ))}
      {/* <Contact / */}
      <Footer address={"Sign up for our monthly newsletter"} />
      <Bottom />
    </div>
  );
}

export async function getStaticProps() {
  // Run API calls in parallel
  const [articles, categories, homepage, products] = await Promise.all([
    fetchAPI("/articles?featured=true"),
    fetchAPI("/categories"),
    fetchAPI("/homepage"),
    fetchAPI("/products"),
  ]);

  return {
    props: { articles, categories, homepage, products },
    revalidate: 1,
  };
}
