import Head from "next/head";
import Hero from "../components/hero";
import { About } from "../components/about";
import { FeaturedProducts } from "../components/featuredProducts";

import { BlogWidget } from "../components/blogWidget";
import { Product } from "../types/product";

import { fetchAPI } from "../lib/api";
import { Article } from "../types/article";
import MainLayout from "../layouts/MainLayout";
import { Categories } from "../components/categories";

import { Button } from "../components/button";
import Link from "next/link";

export interface HomeProps {
  articles?: Article[];
  featuredProducts?: Product[];
}

const Home = (props: HomeProps) => {
  // Use the first 4 articles as featured articles
  const featuredArticles = props.articles ? props.articles.slice(0, 4) : [];
  const featuredProducts = props.featuredProducts;

  return (
    <MainLayout>
      <Head>
        <title>Perfect Health Practice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <About />
      <Categories />
      {/* <Products /> */}
      <FeaturedProducts products={featuredProducts} />

      {/* Featured Blogs? */}

      <div className={"bg-primary text-center h-[500px] grid content-center"}>
        <div className={"grid grid-cols-3"}>
          <div className={"col-span-3"}>
            <h1
              className={
                "text-5xl md:text-5xl z-10 text-white font-medium font-karla pb-12"
              }>
              What our clients have to say
            </h1>
          </div>

          <div className={"col-span-3"}>
            <p className={"italic text-2xl text-white font-light"}>
              “Dr Robin is passionate about healing people, finding the cause of{" "}
              <br />
              the problem and then addressing it. He explains everything so well{" "}
              <br />
              really feel that at last there is hope.”
            </p>
          </div>
        </div>
        <div className={"grid grid-cols-3 h-20 items-center"}>
          <div className={""}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className={
                "h-7 w-7 bg-white rounded-full float-right	 fill-current text-primary"
              }
              viewBox="0 0 20 20"
              fill="currentColor">
              <path
                fill-rule="evenodd"
                d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                clip-rule="evenodd"
              />
            </svg>
          </div>
          <div className={"flex justify-center"}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className={"h-10 w-10  fill-current text-white"}
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z"
              />
            </svg>
          </div>
          <div className={""}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className={
                "h-7 w-7 bg-white rounded-full	 fill-current text-primary"
              }
              viewBox="0 0 20 20"
              fill="currentColor">
              <path
                fill-rule="evenodd"
                d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                clip-rule="evenodd"
              />
            </svg>
          </div>
        </div>
      </div>

      <div className={"h-auto mlg:h-[700px] py-20 "}>
        <div className={"font-karla"}>
          <h1
            className={
              " flex flex-col items-center md:text-5xl pb-20 font-medium text-4xl text-primary md:text-left "
            }>
            Our latest Blogs
          </h1>
        </div>

        <div
          className={
            "bg-white-800 p-2 md:grid grid-cols-4 gap-8 md:px-28 py-2 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-4  "
          }>
          {featuredArticles.map((entry) => {
            return <BlogWidget key={entry.id} article={entry} />;
          })}
          {featuredArticles.length === 0 && (
            <div>Check back soon for some featured articles</div>
          )}
        </div>
        <div
          className={
            "flex flex-col items-start md:items-center pt-10 px-10 md:pt-20 "
          }>
          <Link href="/blogs">
            <a>
              <Button color="primary">Learn more</Button>
            </a>
          </Link>
        </div>
      </div>
    </MainLayout>
  );
};

export default Home;

export async function getStaticProps() {
  // Run API calls in parallel
  const [articles, featuredProducts, categories] = await Promise.all([
    fetchAPI("/articles?featured=true"),
    fetchAPI("/products?featured=true"),
    fetchAPI("/article-categories"),
  ]);

  return {
    props: { articles, featuredProducts, categories },
    revalidate: 1,
  };
}
