import Head from "next/head";
import { About } from "../components/about";
import { FeaturedProducts } from "../components/featuredProducts";

import { BlogWidget } from "../components/blogWidget";
import { Product } from "../types/product";

import { fetchAPI } from "../lib/api";
import { Article } from "../types/article";
import MainLayout from "../layouts/MainLayout";
import { Categories } from "../components/categories";

import { Button } from "../components/button";
import Link from "next/link";

import { Hero } from "../components/home/hero";
import { TestimonialCarousel } from "../components/home/testimonial";
import { useEffect, useState } from "react";

export interface HomeProps {
  articles?: Article[];
  featuredProducts?: Product[];
}

const Home = (props: HomeProps) => {
  const [loading, setLoading] = useState(false);

  const [featuredArticles, setFeaturedArticles] = useState<Article[]>();
  const [featuredProducts, setFeaturedProducts] = useState<Product[]>();

  const fetchData = async () => {
    const [featuredArticles, featuredProducts] = await Promise.all([
      fetchAPI("/articles?featured=true"),
      fetchAPI("/products?featured=true"),
    ]);

    return {
      featuredArticles,
      featuredProducts,
    };
  };

  useEffect(() => {
    try {
      setLoading(true);
      // fetch data
      fetchData().then((result) => {
        // Use the first 4 articles as featured articles
        setFeaturedArticles(result.featuredArticles.slice(0, 4));
        setFeaturedProducts(result.featuredProducts);
      }).finally(() => {
        setLoading(false);
      });
    } catch (e) {
      console.error(`Could not fetch data:`, e);
    }

  }, []);

  return (
    <MainLayout>
      <Head>
        <title>Perfect Health Practice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <About />
      <Categories />
      {/* FeaturedProducts */}
      <FeaturedProducts products={featuredProducts} loading={loading} />

      {/* Testimonials (What our clients have to say) */}
      <div className={"bg-primary text-center h-[500px] grid content-center"}>
        <TestimonialCarousel />
      </div>

      {/* Blogs */}
      <div className={"h-auto mlg:h-[700px] py-20 "}>
        <div className={"font-karla"}>
          <h1
            className={
              " flex flex-col items-center md:text-5xl pb-20 font-medium text-4xl text-primary md:text-left "
            }>
            Our latest Blogs
          </h1>
        </div>

        <div
          className={
            "bg-white-800 p-2 md:grid grid-cols-4 gap-8 md:px-28 py-2 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-4  "
          }>
          {featuredArticles && featuredArticles.map((entry) => {
            return <BlogWidget key={entry.id} article={entry} />;
          })}
          {loading && (
            <div className={"text-gray-600 animate-pulse"}>Fetching featured articles</div>
          )}
          {!loading && (featuredArticles === undefined || featuredArticles.length === 0) && (
            <div>Check back soon for some featured articles</div>
          )}
        </div>
        <div
          className={
            "flex flex-col items-start md:items-center pt-10 px-10 md:pt-20 "
          }>
          <Link href="/blogs">
            <a>
              <Button color="primary">Read more</Button>
            </a>
          </Link>
        </div>
      </div>
    </MainLayout>
  );
};

export default Home;
